version: '3.8'
networks:
  backend:
    name: ${PREFIX}.${APP_ENV} 
services:
  nginx:
    container_name: ${PREFIX}.${APP_ENV}.nginx
    build:
      context: ../../docker/nginx
      target: local
    image: ${PREFIX}.${APP_ENV}/nginx
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ../../src:/var/www:cached
    depends_on:
      - php-fpm
    networks:
      - backend
  php-fpm:
    container_name: ${PREFIX}.${APP_ENV}.php-fpm
    build:
      context: ../../docker/php-fpm
    image: ${PREFIX}.${APP_ENV}/php-fpm
    volumes:
      - ../../src:/var/www:cached
    environment:
      TZ: "Asia/Tokyo"
    networks:
      - backend
  mysql:
    container_name: ${PREFIX}.${APP_ENV}.mysql
    image: mysql:5.7
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: default
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel_db
      TZ: "Asia/Tokyo"
    ports:
      - 3307:3306
    networks:
      - backend
  mailhog:
    container_name: ${PREFIX}.${APP_ENV}.mailhog
    image: 'mailhog/mailhog:latest'
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - backend
